name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          # .env 파일 생성
          echo "WEATHER_API_KEY=${WEATHER_API_KEY}" > .env
          # js 폴더로 이동
          cd js
          # apikey.js 실행
          node apikey.js
